### ISSUE TITLE
Best-practice change

### ISSUE THREAD

**Issue by imrein** [bpmb82/docker-collection#1]
I would like to suggest changing the first task in every service role to the correct ansible module.
FROM:
```yaml
- name: Create folders
  shell: mkdir -p {{ workdir }}/{{ service }}/config
```

TO:
```yaml
- name: Create folders
  file:
    path: "{{ workdir }}/{{ service }}/config"
    recurse: true
    state: directory
    mode: 0755
```
It's best practice to use the build-in ansible modules as much as possible. :smile:
